main.py
from flask import Flask, render_template, redirect, request
from routes.archive import archiveRoutes
from routes.forecast import forecastRoutes
from routes.misc import miscRoutes
from backend.getGEO import geocode



def page_not_found(e):
    return render_template("404.html"), 404

def weatherApp():
    app = Flask(__name__)
    @app.before_request
    def lowercase_redirect():
        path = request.path
        if path.startswith("/static"):
            return
        if path == path.lower():
            return
        lowercase_path = path.lower()
        valid_routes = {rule.rule for rule in app.url_map.iter_rules()}
        if lowercase_path in valid_routes:
            return redirect(lowercase_path, code=301)
    app.register_blueprint(archiveRoutes)
    app.register_blueprint(forecastRoutes)
    app.register_blueprint(miscRoutes)
    geocode(app)
    app.register_error_handler(404, page_not_found)

    return app



app = weatherApp()
if __name__ == "__main__":
    app.run(debug=True)
    #app.run(host='0.0.0.0', port=5000, debug=True)

routes/archive.py
from flask import Blueprint
from flask import render_template
from flask import jsonify
from datetime import datetime
from backend.getArchiveData import get_stations, get_wetter
import pandas



archiveRoutes = Blueprint("archive", __name__)



@archiveRoutes.route("/api/v1/<station>/<date>")
def temperatur(station, date):
    wetterdaten = get_wetter(station)
    df = pandas.read_csv(wetterdaten, skiprows=20, parse_dates=["    DATE"])
    temperatur_als_serie = df.loc[df["    DATE"] == date] ["   TG"]
    if temperatur_als_serie.empty:
        temperatur = "keine Daten vorhanden<br> (möglicherweise liegt die Datumseingabe außerhalb des Aufzeichnungszeitraums)"
    else:
        temperatur_wert = temperatur_als_serie.iloc[0] / 10
        if temperatur_wert < -100:
            temperatur = "Für diesen Tag sind keine Daten vorhanden oder wurden als Messerfehler identifiziert"
        else:
            temperatur = temperatur_wert
    try:
        datum_mod = datetime.strptime(str(date), "%Y%m%d").strftime("%d.%m.%Y")
    except ValueError:
        datum_mod = date

    return {"station": station,
            "date": datum_mod,
            "temperature": temperatur}



@archiveRoutes.route("/api/v1/<station>")
def alle_daten_einer_station(station):
    try:
        wetterdaten = get_wetter(station)
        df = pandas.read_csv(wetterdaten, skiprows=20, parse_dates=["    DATE"])
        return df.to_dict(orient="records")
    except FileNotFoundError as e:
        return jsonify({"Error": str(e)}), 404
    except Exception as e:
        return jsonify({"Error": f"Fehler beim Lesen der Datei"}), 500



@archiveRoutes.route("/api/v1/yearinput/<stationId>/<year>")
def jahreschart(stationId, year):
    try:
        wetterdaten = get_wetter(stationId)
        df = pandas.read_csv(wetterdaten, skiprows=20)
        df["    DATE"] = df["    DATE"].astype(str)
        jahre = df[df["    DATE"].str.startswith(str(year))].to_dict(orient="records")
        return jahre
    except FileNotFoundError as e:
        return jsonify({"Error": str(e)}), 404
    except Exception as e:
        return jsonify({"Error": f"Fehler beim Erstellen der Charts"}), 500



@archiveRoutes.route("/wetterarchiv")
def wetterarchiv():
    try:
        stationenpfad = get_stations()
        stationen = pandas.read_csv(stationenpfad, skiprows=17)
        stationen.columns = stationen.columns.str.strip()
        stationen = stationen[["STAID", "STANAME"]]
        stationen["STANAME"] = stationen["STANAME"].str.strip().str.upper()
        stationen = stationen.sort_values("STANAME")
        stationen["STANAME_CLEAN"] = stationen["STANAME"].str.strip().str.upper()
        stationen_liste = stationen[["STAID", "STANAME", "STANAME_CLEAN"]].to_dict(orient="records")
        stationen_html = stationen.to_html(index=False)
        jahre = list(range(1860,2022))
        return render_template ("wetterarchiv.html", tabelle=stationen_html, stationen=stationen_liste, jahre=jahre, active_page="wetterarchiv")
    
    except Exception as e:
        return render_template("wetterarchiv.html", fehler=str(e))



@archiveRoutes.route("/api/v1/stationen")
def stationen_api():
    try:
        stationenpfad = get_stations()
        stationen = pandas.read_csv(stationenpfad, skiprows=17)
        stationen.columns = stationen.columns.str.strip()
        stationen = stationen[["STAID", "STANAME"]]
        stationen["STANAME"] = stationen["STANAME"].str.strip().str.upper()
        stationen = stationen.sort_values("STANAME")
        stationen["STANAME_CLEAN"] = stationen["STANAME"].str.strip().str.upper()
        stationen_liste = stationen[["STAID", "STANAME", "STANAME_CLEAN"]].to_dict(orient="records")
        return jsonify(stationen_liste)
    except Exception as e:
        return jsonify({"Error": str(e)}), 500

routes/forecast.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import jsonify
from flask import redirect
from flask import url_for
from datetime import datetime, timedelta, UTC
from backend.getAPI import get_daten



forecastRoutes = Blueprint("forecast", __name__)



@forecastRoutes.route("/vorhersage/<stadt>")
def vorhersage(stadt):
    try:
        tage = 3
        daten = get_daten(stadt, tage)
        offset = timedelta(seconds=daten['timezone'])
        for eintrag in daten["list"]:
            utc_time = datetime.fromtimestamp(eintrag["dt"], tz=UTC)
            local_time = utc_time + offset
            eintrag['local_time'] = local_time.strftime('%Y-%m-%d %H:%M')
        return jsonify(daten)
    except Exception as e:
        return jsonify({"error": str(e)})



@forecastRoutes.route("/wettervorhersage", methods=["GET", "POST"])
def wettervorhersage_3_Tage():
    if request.method == "POST":
        stadt = request.form.get("stadt")
        return redirect(url_for("forecast.wettervorhersage_3_Tage", stadt=stadt))
    
    stadt = request.args.get("stadt")
    if not stadt:
        return render_template("wettervorhersage.html", active_page="vorhersage")
    tage = 3
    try:
        daten = get_daten(stadt, tage)
        offset = timedelta(seconds=daten['timezone'])
        for eintrag in daten["list"]:
            utc_time = datetime.fromtimestamp(eintrag["dt"], tz=UTC)
            local_time = utc_time + offset
            eintrag['local_time'] = local_time.strftime('%Y-%m-%d %H:%M')
        return render_template("wettervorhersage.html", daten=daten["list"], stadt=stadt, tage=tage)
    except Exception as e:
        return render_template("wettervorhersage.html", fehler=str(e))

routes/misc.py
from flask import Blueprint
from flask import render_template



miscRoutes = Blueprint("misc", __name__)



@miscRoutes.route("/")
def home():
    return render_template("home.html", active_page="home")



@miscRoutes.route("/impressum")
def impressum():
    return render_template ("impressum.html", active_page="impressum")



@miscRoutes.route("/datenschutz")
def datenschutz():
    return render_template ("datenschutz.html", active_page="datenschutz")

templates/datenschutz.html
{% extends "layouts/index.html" %}
{% block content %}
    <div class="page-wrapper fade">
        <div class="main-wrapper-misc">
            <main class="content">
                <h1 class="misc-text1">
                    Datenschutz
                </h1>

                <p class="misc-textMain">
                    <b class="misc-textMain-Fett">1. Verantwortlicher</b><br>
                    Martin Günther<br>
                    D 10318 - Berlin<br>
                    E-Mail: &nbsp;<span id="email"></span>
                    <noscript><span class="noscript-email">Protools1802 [ät] gmail [punkt] com</span></noscript><br>
                    <br>
                    <b class="misc-textMain-Fett">2. Zugriffsdaten/Server-Logs</b><br>
                    Beim Besuch dieser Website werden durch den Hosting-Anbieter automatisch Informationen erhoben und in Logfiles gespeichert:<br>
                    - IP-Adresse des aufrufenden Geräts<br>
                    - Datum und Uhrzeit des Zugriffs<br>
                    - aufgerufene Seite bzw. Datei<br>
                    - Browsertyp und -version<br>
                    - verwendetes Betriebssystem<br>
                    - Referrer-URL (falls vorhanden)<br>
                    Diese Daten sind technisch erforderlich, um die Website bereitzustellen und die Sicherheit des Servers zu gewährleisten. Eine Zusammenführung 
                    dieser Daten mit anderen Datenquellen findet nicht statt. Die Logfiles werden automatisch archiviert. Rechtsgrundlage: Art. 6 Abs. 1 lit. f DSGVO 
                    (berechtigtes Interesse an einer sicheren und stabilen Bereitstellung der Website).<br>
                    <br>
                    <b b class="misc-textMain-Fett">3. Keine Cookies/Tracking-Tools</b><br>
                    Auf dieser Website werden keine Cookies gesetzt und keine Analyse- oder Trackingdienste eingesetzt.<br>
                    <br>
                    <b class="misc-textMain-Fett">4. Nutzung externer Dienste</b><br>
                    Diese Website nutzt externe Dienste, um die angezeigten Inhalte bereitzustellen:<br>
                    <br>
                    <b><u>OpenWeatherMap API</u></b><br>
                    Zur Anzeige aktueller Wetterdaten wird eine Schnittstelle (API) des Dienstes  „OpenWeatherMap“ (OpenWeather Ltd., UK) verwendet. Beim Abruf 
                    der Wetterdaten wird eine Anfrage an die Server von OpenWeatherMap gesendet. Dabei wird technisch bedingt auch die IP-Adresse des aufrufenden 
                    Geräts übermittelt.<br>
                    Die Daten werden ausschließlich zur Bereitstellung der Wetterinformationen genutzt. Rechtsgrundlage: Art. 6 Abs. 1 lit. f DSGVO (berechtigtes 
                    Interesse an einer funktionalen Darstellung der Wetterdaten).<br>
                    <br>
                    <b><u>Einbindung von Chart.js über CDN</u></b><br>
                    Zur grafischen Darstellung der Wetterdaten wird die JavaScript-Bibliothek „Chart.js“ über ein Content Delivery Network (CDN) geladen. Beim Aufruf 
                    der Datei wird eine Verbindung zu Servern des CDN-Anbieters hergestellt, wodurch technisch bedingt die IP-Adresse des aufrufenden Geräts übermittelt 
                    wird.<br>
                    Die Einbindung erfolgt, um eine schnelle und stabile Auslieferung der Inhalte zu gewährleisten. Rechtsgrundlage: Art. 6 Abs. 1 lit. f DSGVO.
                    <br>
                    Es findet keine weitergehende Verarbeitung personenbezogener Daten durch diese Website statt.<br>
                    <br>
                    <b b class="misc-textMain-Fett">5. Externe Links</b><br>
                    Diese Website enthält ausschließlich Links zu meiner eigenen Website. Beim Anklicken des Links verlassen Sie diese Website. Für die Verarbeitung 
                    personenbezogener Daten auf der verlinkten Seite ist ausschließlich der jeweilige Betreiber (also auch ich) verantwortlich.<br>
                    <br>
                    <b b class="misc-textMain-Fett">6. Rechte der betroffenen Person</b><br>
                    Sie haben nach DSGVO folgende Rechte:<br>
                    - Recht auf Auskunft über die verarbeiteten personenbezogenen Daten<br>
                    - Recht auf Berichtigung<br>
                    - Recht auf Löschung<br>
                    - Recht auf Einschränkung der Verarbeitung<br>
                    - Recht auf Widerspruch<br>
                    - Recht auf Datenübertragbarkeit<br>
                    Zur Ausübung dieser Rechte genügt eine formlose Mitteilung an die oben genannte Kontaktadresse.<br>
                    <br>
                </p>
            </main>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends "layouts/index.html" %}
{% set no_topbar = True %}
{% set no_footer = True %}
{% block content %}
    <div class="page-wrapper fade">
        <div class="main-wrapper-home">
            <main class="content">
                <h1 class="banner">WetterApp</h1>
                <div class="home-kacheln">
                    <a href="{{url_for('archive.wetterarchiv')}}" class="card-link">
                        <div class="card">
                            <img src="{{ url_for('static', filename='Wetterarchiv.png') }}" class="portrait" alt="Wetterarchiv">
                            <h1>Wetterarchiv</h1>
                            <p>Abfrage von historischen Temperaturen europäischer Wetterstationen von 1860 bis 2022.</p>
                        </div>
                    </a>
                    <a href="{{url_for('forecast.wettervorhersage_3_Tage')}}" class="card-link">
                        <div class="card">
                            <img src="{{ url_for('static', filename='WetterAPI.png') }}" class="portrait" alt="Wetter API">
                            <h1>Wettervorhersage</h1>
                            <p>Wettervorhersage für die nächsten 3 Tage.</p>
                        </div>
                    </a>
                </div>
            </main>
        </div>
    </div>
{% endblock %}

templates/impressum.html
{% extends "layouts/index.html" %}
{% block content %}
    <div class="page-wrapper fade">
        <div class="main-wrapper-misc">
            <main class="content">
                <h1 class="misc-text1">
                    Impressum
                </h1>

                <h2 class="misc-text2">
                    Webseiteninhaber:
                </h2>

                <h3 class="misc-text3">
                    Martin Günther<br>
                    D 10318 - Berlin<br>
                    E-Mail: &nbsp;<span id="email"></span>
                    <noscript><span class="noscript-email">Protools1802 [ät] gmail [punkt] com</span></noscript>
                </h3>

                <p class="misc-text4">
                    <b class="misc-text4-sub">
                        Haftungsausschuss:
                    </b>
                    <br>
                </p>

                <p class="misc-textMain">
                    <b class="misc-textMain-Fett">Haftung für Inhalte</b><br>
                    Die Inhalte dieser Seite wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte kann ich jedoch 
                    keine Gewähr übernehmen. Gemäß § 7 Abs.1 Digitale-Dienste-Gesetz (DDG) bin ich für eigene Inhalte verantwortlich, aber gemäß §§ 8 bis 10 DDG bin 
                    ich nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige 
                    Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon 
                    unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von 
                    entsprechenden Rechtsverletzungen werde ich diese Inhalte umgehend entfernen.<br>
                    <br>
                    <b b class="misc-textMain-Fett">Urheberrecht</b><br>
                    Sofern nicht anders gekennzeichnet, stelle ich diese Inhalte zur privaten und kommerziellen Nutzung frei.<br>
                    Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte 
                    Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten ich um entsprechende Hinweise, 
                    damit ich derartige Inhalte umgehend entfernen kann oder mit entsprechenden Quellennachweis versehen kann.<br>
                    Abschließend weise ich ausdrücklich  darauf hin, dass die bereitgestellte Webseite ohne jegliche Gewährleistung zur Verfügung gestellt wird.<br>
                    <br>
                    Die Nutzung erfolgt auf eigene Gefahr. Ich übernehme keinerlei Haftung für Schäden, die durch die Nutzung entstehen.</br>
                    <br>
                    <b b class="misc-textMain-Fett">Datenschutz</b><br>
                    Diese Webseite benutzt keine Cookies, Disclaimers, Analysetools o.ä. Die Nutzung ist ganz ohne Angabe von personenbezogenen Daten möglich.
                    Eingaben in die Suchfelder vom Wetterarchiv und der Wettervorhersage werden weder gespeichert noch getrackt oder analysiert. Es gilt allerdings 
                    zu beachten, dass ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte technisch nicht möglich ist.<br>
                    <br>
                    Es ist ausdrücklich nicht erwünscht, dass über die im Impressum veröffentlichten Kontaktdaten Werbung ("Spam") übermittelt wird!<br>
                    <br>
                </p>
            </main>
        </div>
    </div>
{% endblock %}

templates/layouts/footer.html
    <footer class="footer">
        <ul>
            <li><a href="https://www.mguenther-build.de" target="_blank" rel="noopener noreferrer">MGuenther-build.de</a></li>
            <li class="{% if request.path == '/Impressum' %}active{% endif %}"><a href="{{ url_for('misc.impressum') }}">Impressum</a></li>
            <li class="{% if request.path == '/Datenschutz' %}active{% endif %}"><a href="{{ url_for('misc.datenschutz') }}">Datenschutz</a></li>
        </ul>
    </footer>

templates/layouts/index.html
<!DOCTYPE html>
<html lang="de">
<head>
  <title>{% block title %}WetterApp{% endblock %}</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="WetterApp von Martin Günther. Historische Wetterdaten und aktuelle Wettervorhersagen.">
  <link rel="preload" href="{{ url_for('static', filename='styles.css') }}" as="style">
  <link rel="icon" href="{{ url_for('static', filename='Favicon_Wetter.png') }}" type="image/png">
  <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
  <script type="application/ld+json">
    {
      "@context": "https://schema.org",
      "@type": "Person",
      "name": "Martin Günther",
      "jobTitle": "Softwareentwickler",
      "address": {
          "@type": "PostalAddress",
          "addressLocality": "Berlin",
          "addressCountry": "DE"
      },
      "url": "https://wetterapp.mguenther-build.de",
      "sameAs": [ "https://github.com/MGuenther-build" ]
    }
  </script>
  <script src="{{ url_for('static', filename='js/script.js') }}" defer></script>
  {% block specificScript %}{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/chart.js" defer></script>
  <script src="{{ url_for('static', filename='js/wetterarchiv.js') }}" defer></script>
  <script src="{{ url_for('static', filename='js/wettervorhersage.js') }}" defer></script>
</head>
<body>
  <div id="topbar" class="{% if no_topbar %}hidden{% endif %}">
{% include "layouts/topbar.html" %}
  </div>
  {% block content %}{% endblock %}
  <div id="footer" class="{% if no_footer %}hidden{% endif %}">
{% include "layouts/footer.html" %}
</body>
</html>

templates/layouts/topbar.html
    <nav class="topbar">
      <div class="menu-toggle" id="mobile-menu">☰</div>
      <ul>
          <li class="{% if request.path == '/Home' %}active{% endif %}"><a href="{{ url_for('misc.home') }}">Home</a></li>
          <li class="{% if request.path == '/Wetterarchiv' %}active{% endif %}"><a href="{{ url_for('archive.wetterarchiv') }}">Wetterarchiv</a></li>
          <li class="{% if request.path == '/3-Tage-Wetter' %}active{% endif %}"><a href="{{ url_for('forecast.wettervorhersage_3_Tage') }}">Vorhersage</a></li>
      </ul>
    </nav>

templates/wetterarchiv.html
{% extends "layouts/index.html" %}
{% block content %}
    <div class="page-wrapper fade">
        <div class="main-wrapper-archiv">
            <main class="content">
                <h1 class="banner-archiv">Wetterarchiv</h1>
                <form id="wetterForm">
                    <div class="form-group">
                        <p class="abfrage-label">Abfrage starten</p>
                        <br>
                    <label for="stationInput">📍 Wetterstation:</label>
                        <input type="text" id="stationInput" list="stationenList" title="Ort eingeben oder wählen" placeholder="Ort eingeben oder wählen …" required>
                        <datalist id="stationenList">
                        {% for station in stationen %}
                            <option value="{{station.STANAME}}" data-staid="{{station.STAID}}"></option>
                        {% endfor %}
                        </datalist>
                    </div>

                    <div class="form-group">
                        <label for="date">📅 Datum:</label>
                        <input type="text" id="date" name="date" placeholder="z.B. 25.10.1988">
                    </div>
                    <button type="submit">🌡️ Temperatur abrufen</button>
                </form>
                <div id="result"></div>
                <div id="chartWrapper">
                    <div id="chartContainer">
                        <h2>Höchsttemperatur</h2>
                        <div id="chartInfo"></div>
                        <h2>📈 Jahresverlauf für <span id="yearLabel"></span></h2>
                        <canvas id="chart"></canvas>
                        <button id="scrollTopBtn" class="scroll-top-btn">↑ nach oben ↑</button>
                    </div>
                </div>

                <div class="info-wrapper">
                    <p class="wetterarchiv-info">Bitte bedenken Sie, dass es sich hier um eine Sammlung aller europäischen Wetterstationen handelt, die seit 1860 bis 2022 
                        Messungen vornahmen. Einige von ihnen sind schon lange nicht mehr in Betrieb, andere waren nur wenige Jahre in Betrieb oder immer mal wieder 
                        (doppelte Einträge!).
                    </p>
                </div>
            </main>
        </div>
    </div>
{% endblock %}

templates/wettervorhersage.html
{% extends "layouts/index.html" %}
{% block content %}
    <div class="page-wrapper fade">
        <div class="main-wrapper-vorhersage">
            <main class="content">
                <h1 class="banner-vorhersage">3-Tage-Wetter</h1>
                <form id="wetterFormVorhersage">
                    <div class="wettervorhersage-container fade">
                        <div class="autocomplete-wrapper">
                            <input type="text" id="stadt" name="stadt" class="input-wettervorhersage" title="Ort eingeben" placeholder="z.B. Tokyo" required autocomplete="off">
                            <ul id="autocomplete-list" class="autocomplete-list"></ul>
                            <button type="submit" class="button-wettervorhersage" title="Wetter abfragen">Ok</button>
                        </div>
                    </div>
                </form>
                <div id="forecast-output" class="output fade"></div>
            </main>
        </div>
    </div>
{% endblock %}